---
deployment:
  tasks:
    - export DEPLOYPATH=/home/manishamaniar65/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R layout $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH